
WINDOW_WIDTH = 323
WINDOW_HEIGHT = 639

POST_WIDTH = 282
POST_HEIGHT = 262
POST_X_POS = 20
POST_Y_POS = 130

LIKE_BUTTON_X_POS = 34
LIKE_BUTTON_Y_POS = 399
LIKE_BUTTON_WIDTH = 19
LIKE_BUTTON_HEIGHT = 17

COMMENT_BUTTON_X_POST = 64
COMMENT_BUTTON_Y_POS = 399
COMMENT_BUTTON_WIDTH = 17
COMMENT_BUTTON_HEIGHT = 17

USER_NAME_X_POS = 56
USER_NAME_Y_POS = 100

LOCATION_TEXT_X_POS = 56
LOCATION_TEXT_Y_POS = 110

DESCRIPTION_TEXT_X_POS = 34
DESCRIPTION_TEXT_Y_POS = 440

LIKE_TEXT_X_POS = 34
LIKE_TEXT_Y_POS = 425

VIEW_MORE_COMMENTS_X_POS = 34
VIEW_MORE_COMMENTS_Y_POS = 532
VIEW_MORE_COMMENT_HEIGHT = 15
VIEW_MORE_COMMENT_WIDTH = 105

FIRST_COMMENT_X_POS = 34
FIRST_COMMENT_Y_POS = 455
COMMENT_LINE_HEIGHT = 13

TEXT_POST_FONT_SIZE = 35

NUM_OF_COMMENTS_TO_DISPLAY = 6

COMMENT_TEXT_SIZE = 15
COMMENT_DISPLAY_X_POS = 12
FIRST_COMMENT_DISPLAY_Y_POS = 480

LINE_MAX_LENGTH = 20